# Uncomment the next line to define a global platform for your project

 platform :ios, '13.0'

target 'DyteUiKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'DyteiOSCore' , '0.6.9'
  # Pods for DyteUiKit

  target 'DyteUiKitTests' do
    # Pods for testing
  end

end
